spring:
  application:
    name: configuration-server
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/tronkiller1919/SunDev_Config.git
          default-label: main
          cloneOnStart: true

server:
  port: 8995

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

